# Generated by Django 3.2.18 on 2023-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='race',
            name='name',
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='equipment',
            field=models.ManyToManyField(help_text='Añada un objeto', to='roleapp.Item'),
        ),
    ]
