# Generated by Django 3.2.18 on 2023-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0002_auto_20230519_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='name',
            field=models.CharField(choices=[('1', 'Barbarian'), ('2', 'Bard'), ('3', 'Cleric'), ('4', 'Druid'), ('5', 'Fighter'), ('6', 'Monk'), ('7', 'Paladin'), ('8', 'Ranger'), ('9', 'Rogue'), ('10', 'Sorcerer'), ('11', 'Warlock'), ('12', 'Wizard')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magicitem',
            name='rarity',
            field=models.CharField(choices=[('1', 'Common'), ('2', 'Uncommon'), ('3', 'Rare'), ('4', 'Very rare'), ('5', 'Legendary'), ('6', 'Artifact'), ('7', 'Unknown')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('1', 'Human'), ('2', 'Half Orc'), ('3', 'Elf'), ('4', 'Dwarf'), ('5', 'Halfling')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
