# Generated by Django 3.2.18 on 2023-05-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0004_alter_characterclass_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], max_length=30),
        ),
    ]
