# Generated by Django 3.2.10 on 2023-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0005_alter_characterclass_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='subClass',
            field=models.CharField(choices=[('Prueba', 'Prueba'), ('Prueba2', 'Prueba2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='magicitem',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Very rare', 'Very rare'), ('Legendary', 'Legendary'), ('Artifact', 'Artifact'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Human', 'Human'), ('Half Orc', 'Half Orc'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Halfling', 'Halfling')], max_length=30),
        ),
    ]
