# Generated by Django 3.2.10 on 2023-05-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0006_auto_20230526_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
