# Generated by Django 3.2.10 on 2023-05-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0008_auto_20230526_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='setAtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('characterSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.charactersheet')),
            ],
        ),
    ]
