# Generated by Django 3.2.10 on 2023-05-31 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0009_setatt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='MagicItem',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
    ]
