# Generated by Django 3.2.10 on 2023-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0011_armor_magicitem_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='attribute',
            field=models.CharField(choices=[('DEX', 'Dexterity'), ('STR', 'Strength')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='magicitem',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Very rare', 'Very rare'), ('Legendary', 'Legendary'), ('Artifact', 'Artifact'), ('Unknown', 'Unknown')], max_length=20),
        ),
    ]
