# Generated by Django 3.2.10 on 2023-05-31 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('roleapp', '0012_auto_20230531_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='magicitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='item',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_roleapp.item_set+', to='contenttypes.contenttype'),
        ),
    ]
