# Generated by Django 3.2.10 on 2023-06-04 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roleapp', '0013_auto_20230601_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='subClass',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='characterClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterClass', to='roleapp.characterclass'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='roleapp.Item'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race', to='roleapp.race'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='setAtt',
        ),
    ]
