# Generated by Django 3.2.10 on 2023-06-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0014_auto_20230604_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='alignment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='currentHitPoints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='experiencePoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='isInspired',
            field=models.BooleanField(default=False),
        ),
    ]
