# Generated by Django 3.2.10 on 2023-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('registerDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
